# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c48998eee38600bddc51556d6a25df10"
name = "InvoiceKing"
application_url = "https://invoice-king-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

  # Handled by: /app/routes/webhooks.app.uninstalled.tsx
  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  # Handled by: /app/routes/webhooks.app.scopes_update.tsx
  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"

  # Mandatory compliance topics for public apps
  # See: https://shopify.dev/docs/apps/build/privacy-law-compliance
  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = ["customers/data_request"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = ["customers/redact"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = ["shop/redact"]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_draft_orders,read_customers,read_products,read_locales"

[auth]
redirect_urls = [ "https://invoice-king-production.up.railway.app/auth/callback", "https://invoice-king-production.up.railway.app/auth/shopify/callback", "https://invoice-king-production.up.railway.app/api/auth/callback" ]
